data-storage: FLATFILE #FLATFILE | SQL | MONGO
mongo:
  host: localhost
  port: 27017
  db: TeamsPlus
  auth:
    enabled: false
    username: default
    password: default
sql:
  username: default
  password: default
  db: default
  url: localhost
  port: 3306

invite-seconds: 30

chat:
  custom-chat: true
  ping-player-on-mention: true
  custom:
    format-global-inteam: '%1[%2] %3&r: %4' # %1 - color (green if team, blue if neutral, purple if ally, red if enemy) | %2 - team name | %3 player | %4 - message
    format-global-noteam: '%1%2: %4' # %1 - color (green if themself, blue if neutral, purple if ally, red if enemy) | %2 - name | %3 - message
    format-team: '&7[&aTeam&7] &a%1%r: %2'
    format-ally: '&7[&dAlly&7] &a%1%r: %2'
team:
  temp-pvp: #teams can do /team temppvp to enable pvping teammates, for duels etc...
    enable: true
    seconds: 300
  blocked-names:
    - player # messes with the /team info command
    - self #
ally:
  request-timeout: 300 # 5 minutes
pvp:
  pvp-team: false
  pvp-ally: false