data-storage: FLATFILE #FLATFILE | SQL | MONGO
mongo:
  host: localhost
  port: 27017
  db: TeamsPlus
  auth:
    enabled: false
    username: default
    password: default
sql:
  username: default
  password: default
  db: default
  url: localhost
  port: 3306

invite-seconds: 30

chat:
  enable: true
  ping-player-on-mention: true

team:
  temp-pvp: #teams can do /team temppvp to enable pvping teammates, for duels etc...
    enable: true
    seconds: 300
  blocked-names:
    - player # messes with the /team info command
    - self #
  max-name-length: 16
ally:
  request-timeout: 300 # 5 minutes
pvp:
  pvp-team: false
  pvp-ally: false
enable-vanish-hook: true
waypoint:
  allowed-icons:
    - NAME_TAG
    - REDSTONE
    - STRING
    - SADDLE
    - SALMON
    - OAK_LOG
    - OBSIDIAN
    - BEACON
    - COOKED_BEEF
    - NETHERRACK
    - HOPPER
    - GOLDEN_SWORD
    - GOLD_NUGGET
    - NETHERITE_PICKAXE
    - NETHERITE_SWORD
    - NETHERITE_AXE
    - CRAFTING_TABLE
    - ANVIL
    - ENCHANTING_TABLE
    - BOOKSHELF
    - ENDER_EYE
  default-icon: NAME_TAG
